server:
  servlet:
    context-path: /library
spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
upload:
  path: /home/vitalii/Templates/storage
  context: images