server:
  servlet:
    context-path: /library
spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: none
upload:
  path: /home/vitalii/Templates/storage
  context: images
constraint:
  password:
    min: "5"
    max: "30"
    pattern: "[a-zA-Z0-9]+"
user:
  name: ladmin
  password: lPassword
  email: ladmin@service.com