server:
  servlet:
    context-path: /library
spring:
  data:
    rest:
      base-path: /api
      default-page-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:${db-port}/${db-name}
    hikari:
      password: ${db-password}
      username: ${db-username}
  flyway:
    user: ${db-username}
    password: ${db-password}
upload:
  path: ${file-storage}
  context: images
constraint:
  password:
    min: "5"
    max: "30"
    pattern: "[a-zA-Z0-9]+"
user:
  name: ladmin
  password: lPassword
  email: ladmin@service.com